services:
  airelogic.panda.api:
    image: ${DOCKER_REGISTRY-}airelogicpandaapi
    build:
      context: .
      dockerfile: AireLogic.PANDA.API/Dockerfile
    ports:
    - 5000:8080
    - 5001:8081

  airelogic.panda.sql.db:
    container_name: panda-sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "MySaPassword123"
      MSSQL_PID: "Evaluation"
    ports:
      - "1433:1433"