// <auto-generated>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace AireLogic.PANDA.API.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "PANDA");

            migrationBuilder.CreateTable(
                name: "Clinicians",
                schema: "PANDA",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    Department = table.Column<string>(type: "varchar(100)", unicode: false, maxLength: 100, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Clinicians", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Patients",
                schema: "PANDA",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    NhsNumber = table.Column<string>(type: "varchar(16)", unicode: false, maxLength: 16, nullable: false),
                    Title = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    FirstName = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    Surname = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    DateOfBirth = table.Column<DateOnly>(type: "date", nullable: false),
                    Postcode = table.Column<string>(type: "varchar(8)", unicode: false, maxLength: 8, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Patients", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Appointments",
                schema: "PANDA",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    PatientId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ClinicianId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Status = table.Column<int>(type: "int", nullable: false),
                    StartTime = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    EndTime = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    Duration = table.Column<int>(type: "int", nullable: false),
                    Department = table.Column<string>(type: "varchar(50)", unicode: false, maxLength: 50, nullable: false),
                    Postcode = table.Column<string>(type: "varchar(8)", unicode: false, maxLength: 8, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Appointments", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Appointments_Clinicians_ClinicianId",
                        column: x => x.ClinicianId,
                        principalSchema: "PANDA",
                        principalTable: "Clinicians",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Appointments_Patients_PatientId",
                        column: x => x.PatientId,
                        principalSchema: "PANDA",
                        principalTable: "Patients",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                schema: "PANDA",
                table: "Clinicians",
                columns: new[] { "Id", "Department", "Name" },
                values: new object[,]
                {
                    { new Guid("9eafd270-8071-4a09-85ba-f040a7b57e90"), "oncology", "Bethany Rice-Hammond" },
                    { new Guid("b7fd5c25-61d6-4634-82f0-e18f27b51f2a"), "oncology", "Jason Holloway" },
                    { new Guid("b85fa2f9-faff-4ed2-b69b-7e5c198e65be"), "gastroentology", "Joseph Savage" }
                });

            migrationBuilder.InsertData(
                schema: "PANDA",
                table: "Patients",
                columns: new[] { "Id", "DateOfBirth", "FirstName", "NhsNumber", "Postcode", "Surname", "Title" },
                values: new object[,]
                {
                    { new Guid("1929d3cf-83c1-487a-838f-c42c023ec42f"), new DateOnly(2002, 2, 12), "Bryan", "0021403597", "M4 2ST", "Hall", "Dr" },
                    { new Guid("892bde48-96da-4bad-8114-a7fe62109462"), new DateOnly(1963, 8, 27), "Ian", "1953262716", "WA55 8HE", "Hall", "Dr" },
                    { new Guid("9a9e8d7e-58d2-4ecc-93f1-4425f1e51bec"), new DateOnly(1996, 2, 1), "Glenn", "1373645350", "N6 2FA", "Clark", "Dr" }
                });

            migrationBuilder.InsertData(
                schema: "PANDA",
                table: "Appointments",
                columns: new[] { "Id", "ClinicianId", "Department", "Duration", "EndTime", "PatientId", "Postcode", "StartTime", "Status" },
                values: new object[,]
                {
                    { new Guid("01542f70-929f-4c9a-b4fa-e672310d7e78"), new Guid("9eafd270-8071-4a09-85ba-f040a7b57e90"), "oncology", 60, new DateTimeOffset(new DateTime(2025, 6, 4, 17, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)), new Guid("892bde48-96da-4bad-8114-a7fe62109462"), "IM2N 4LG", new DateTimeOffset(new DateTime(2025, 6, 4, 16, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)), 1 },
                    { new Guid("343d31d4-5993-47ef-a468-7884a467ae80"), new Guid("b7fd5c25-61d6-4634-82f0-e18f27b51f2a"), "oncology", 15, new DateTimeOffset(new DateTime(2018, 1, 21, 16, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), new Guid("9a9e8d7e-58d2-4ecc-93f1-4425f1e51bec"), "UB56 7XQ", new DateTimeOffset(new DateTime(2018, 1, 21, 16, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), 2 },
                    { new Guid("70ead2bc-40c1-42ef-8d00-60c0b38d0a4e"), new Guid("b85fa2f9-faff-4ed2-b69b-7e5c198e65be"), "gastroentology", 60, new DateTimeOffset(new DateTime(2018, 9, 4, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)), new Guid("1929d3cf-83c1-487a-838f-c42c023ec42f"), "E91 9AE", new DateTimeOffset(new DateTime(2018, 9, 4, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)), 2 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Appointments_ClinicianId",
                schema: "PANDA",
                table: "Appointments",
                column: "ClinicianId");

            migrationBuilder.CreateIndex(
                name: "IX_Appointments_PatientId",
                schema: "PANDA",
                table: "Appointments",
                column: "PatientId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Appointments",
                schema: "PANDA");

            migrationBuilder.DropTable(
                name: "Clinicians",
                schema: "PANDA");

            migrationBuilder.DropTable(
                name: "Patients",
                schema: "PANDA");
        }
    }
}
